version: '3'
services:
  react-ui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: fcdc-frontend
    stdin_open: true
    volumes:
      - ./:/app
      - /node_modules